// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClR7_ABmRRpumVDk6HTmRRHAkjf_r7LPg',
    appId: '1:361947207528:web:d2f1f5974594a49b9ea8dd',
    messagingSenderId: '361947207528',
    projectId: 'flutter-chat--app-d5ebd',
    authDomain: 'flutter-chat--app-d5ebd.firebaseapp.com',
    storageBucket: 'flutter-chat--app-d5ebd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNB0sZP2oqKO5NatL6nwu_t2EipBd_W4M',
    appId: '1:361947207528:android:89c881ff88615b8e9ea8dd',
    messagingSenderId: '361947207528',
    projectId: 'flutter-chat--app-d5ebd',
    storageBucket: 'flutter-chat--app-d5ebd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ-xP8yC2JDdU1dt0IQgxtcqiDgUhrQCI',
    appId: '1:361947207528:ios:7a0a25a39bf0e4aa9ea8dd',
    messagingSenderId: '361947207528',
    projectId: 'flutter-chat--app-d5ebd',
    storageBucket: 'flutter-chat--app-d5ebd.appspot.com',
    iosClientId: '361947207528-uv0t1vup3ej51ia1g2h2bjovfhbtmkr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ-xP8yC2JDdU1dt0IQgxtcqiDgUhrQCI',
    appId: '1:361947207528:ios:525195376634408c9ea8dd',
    messagingSenderId: '361947207528',
    projectId: 'flutter-chat--app-d5ebd',
    storageBucket: 'flutter-chat--app-d5ebd.appspot.com',
    iosClientId: '361947207528-n7o0jpcb3s2rgrdcav07oonsl86rpcue.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp.RunnerTests',
  );
}
